objects/Account.object
<CustomObject>
    <sharingModel>ReadWrite</sharingModel>
    <recordTypes>
        <fullName>Master</fullName>
        <active>true</active>
        <label>Master</label>
    </recordTypes>
</CustomObject>

objects/BeBack__c.object
<CustomObject>
    <label>Prospect Note</label>
    <nameField>
        <label>Prospect Note</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Prospect Notes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Cobuyer__c.object
<CustomObject>
    <label>Cobuyer</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cobuyers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <recordTypes>
        <fullName>Opportunity</fullName>
        <active>true</active>
        <label>Opportunity</label>
    </recordTypes>
</CustomObject>

objects/Contigency__c.object
<CustomObject>
    <label>Contingency</label>
    <nameField>
        <displayFormat>C-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contingencies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Lot__c.object
<CustomObject>
    <fields>
        <fullName>Subdivision__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Subdivision</label>
        <referenceTo>Subdivision__c</referenceTo>
        <relationshipLabel>Lots</relationshipLabel>
        <relationshipName>Lots</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Lot</label>
    <nameField>
        <label>Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Lots</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Model__c.object
<CustomObject>
    <fields>
        <fullName>Subdivision__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Subdivision</label>
        <referenceTo>Subdivision__c</referenceTo>
        <relationshipLabel>Models</relationshipLabel>
        <relationshipName>Models</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Model</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Models</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Newstar_Country__c.object
<CustomObject>
    <label>Newstar Country</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Newstar Countries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Newstar_State__c.object
<CustomObject>
    <fields>
        <fullName>Newstar_Country__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>NEWSTAR Country</label>
        <referenceTo>Newstar_Country__c</referenceTo>
        <relationshipLabel>States</relationshipLabel>
        <relationshipName>States</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>NEWSTAR States</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>NEWSTAR States</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Lot__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Lot</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>(1 AND 2 AND 3 AND 4) OR 5</booleanFilter>
            <errorMessage>Lot must belong to the selected subdivision, be available (open) and be released for sale.</errorMessage>
            <filterItems>
                <field>Lot__c.Subdivision__c</field>
                <operation>equals</operation>
                <valueField>$Source.Subdivision__c</valueField>
            </filterItems>
            <filterItems>
                <field>Lot__c.Released_for_Sale__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <filterItems>
                <field>Lot__c.Status__c</field>
                <operation>equals</operation>
                <value>Open</value>
            </filterItems>
            <filterItems>
                <field>$Source.StageName</field>
                <operation>equals</operation>
                <value>Prospecting, Engagement, Quote/Selection</value>
            </filterItems>
            <filterItems>
                <field>$Source.StageName</field>
                <operation>equals</operation>
                <value>Contract Ready, Lot Reservation, Pending Offer, Under Contract, Closed Home, Cancelled, Quote Closed</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Lot__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Model__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Model</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Model must belong to the selected subdivision and must be active.</errorMessage>
            <filterItems>
                <field>Model__c.Subdivision__c</field>
                <operation>equals</operation>
                <valueField>$Source.Subdivision__c</valueField>
            </filterItems>
            <filterItems>
                <field>Model__c.Is_Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Model__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sales_Office__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Sales Office</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Sales_Office__c.Is_Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Sales_Office__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Subdivision__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Project</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Subdivision must belong to the selected sales office and the selected marketing community.</errorMessage>
            <filterItems>
                <field>Subdivision__c.Sales_Office__c</field>
                <operation>equals</operation>
                <valueField>$Source.Sales_Office__c</valueField>
            </filterItems>
            <filterItems>
                <field>Subdivision__c.Marketing_Community__c</field>
                <operation>equals</operation>
                <valueField>$Source.Marketing_Community__c</valueField>
            </filterItems>
            <infoMessage>Select a subdivision</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Subdivision__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Sales_Agent__c.object
<CustomObject>
    <label>Sales Agent</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Agents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Sales_Office__c.object
<CustomObject>
    <description>NEWSTAR Sales Office</description>
    <label>Sales Office</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Offices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Sales_Office_Customer__c.object
<CustomObject>
    <fields>
        <fullName>Sales_Office__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Sales Office</label>
        <referenceTo>Sales_Office__c</referenceTo>
        <relationshipLabel>Sales Office Customers</relationshipLabel>
        <relationshipName>Sales_Office_Customers</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Sales Office Customer</label>
    <nameField>
        <displayFormat>SOC-{00000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Office Customers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/SalesAgentSalesOfficeLink__c.object
<CustomObject>
    <fields>
        <fullName>Sales_Agent__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Sales Agent</label>
        <referenceTo>Sales_Agent__c</referenceTo>
        <relationshipLabel>Sales Agent Sales Office Relationships</relationshipLabel>
        <relationshipName>Sales_Agent_Sales_Office_Relationships</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sales_Office__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Sales Office</label>
        <referenceTo>Sales_Office__c</referenceTo>
        <relationshipLabel>Sales Agent Sales Office Relationships</relationshipLabel>
        <relationshipName>Sales_Agent_Sales_Office_Relationships</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Sales Agent Sales Office Relationship</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Agent Sales Office Relationships</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Subdivision__c.object
<CustomObject>
    <fields>
        <fullName>Sales_Office__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Sales Office</label>
        <referenceTo>Sales_Office__c</referenceTo>
        <relationshipLabel>Subdivisions</relationshipLabel>
        <relationshipName>Subdivisions</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <description>NEWSTAR Sales Subdivision</description>
    <label>Project</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/SFDataCleanUpService.cls
public with sharing class SFDataCleanUpService {


    public static List<SObject> getObjectsToDelete() {

      
        List<SObject> deleteList=new List<SObject>();


        // ========================= opp child entities first

        //cobuyers
        List<Cobuyer__c> cobuyerList=[SELECT Id, Name FROM Cobuyer__c];
        deleteList.addAll(cobuyerList);

        //contigencies
        List<Contigency__c> contigencyList=[SELECT Id, Name FROM Contigency__c];
        deleteList.addAll(contigencyList);


        //tasks
        List<Task> taskList=[SELECT Id FROM Task];
        deleteList.addAll(taskList);

        //events
        List<Event> eventList=[SELECT Id FROM Event];
        deleteList.addAll(eventList);


        
        //prospect notes (BeBack__c)
        List<BeBack__c> prospectNoteList=[SELECT Id, Name FROM BeBack__c];
        deleteList.addAll(prospectNoteList);

        //opportunities
        List<Opportunity> opportunityList= [SELECT Id, AccountId FROM Opportunity];
        deleteList.addAll(opportunityList);

        //real estate agents (as Contacts)
        List<Contact> agentContactList= [SELECT Id, Name FROM Contact WHERE IsPersonAccount=false];
        deleteList.addAll(agentContactList);


        //customer -> sales office associations
         List<Sales_Office_Customer__c> salesOfficeCustomerList= [SELECT Id, Name FROM Sales_Office_Customer__c];
        deleteList.addAll(salesOfficeCustomerList);
        

        //real estate agencies and customers (as Accounts)
        List<Account> accountList= [SELECT Id, Name FROM Account];
        deleteList.addAll(accountList);


         // ========================= master data

        //lots
        List<Lot__c> lotList= [SELECT Id, Name FROM Lot__c];
        deleteList.addAll(lotList);

        //models
        List<Model__c> modelList= [SELECT Id, Name FROM Model__c];
        deleteList.addAll(modelList);

        //subdivisions
        List<Subdivision__c> subdivisionList= [SELECT Id, Name FROM Subdivision__c];
        deleteList.addAll(subdivisionList);


        //sales agent sales office relationships
        List<SalesAgentSalesOfficeLink__c> salesAgentSalesOfficeRelList= [SELECT Id, Name FROM SalesAgentSalesOfficeLink__c];
        deleteList.addAll(salesAgentSalesOfficeRelList);


        //sales agents
        List<Sales_Agent__c> salesAgentList= [SELECT Id, Name FROM Sales_Agent__c];
        deleteList.addAll(salesAgentList);

        //sales offices
        List<Sales_Office__c> salesOfficeList= [SELECT Id, Name FROM Sales_Office__c];
        deleteList.addAll(salesOfficeList);


        //NEWSTAR states
        List<Newstar_State__c> stateList= [SELECT Id, Name FROM Newstar_State__c];
        deleteList.addAll(stateList);

        //NEWSTAR countries
        List<Newstar_Country__c> countryList= [SELECT Id, Name FROM Newstar_Country__c];
        deleteList.addAll(countryList);

        return deleteList;
      
    }


   
}