objects/Account.object
<CustomObject>
    <fields>
        <fullName>Sales_Office_mapping__c</fullName>
        <label>Sales Office mapping</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/BRPSalesSettings__c.object
<CustomObject>
    <fields>
        <fullName>HsFormurl__c</fullName>
        <label>HsFormurl</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sales_Office_Name__c</fullName>
        <label>Sales Office Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SharingType__c</fullName>
        <defaultValue>false</defaultValue>
        <label>SharingType</label>
        <type>Checkbox</type>
    </fields>
    <customSettingsType>List</customSettingsType>
    <label>BRP Sales Settings</label>
</CustomObject>

objects/Marketing_Community__c.object
<CustomObject>
    <fields>
        <fullName>Other_groups_can_Read__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Other groups can Read?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Sales_office__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sales Office</label>
        <referenceTo>Sales_Office__c</referenceTo>
        <relationshipLabel>Marketing Communities</relationshipLabel>
        <relationshipName>Marketing_Communities</relationshipName>
        <type>Lookup</type>
    </fields>
    <description>SiteCore/CMS "marketing community"</description>
    <label>Marketing Community</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Marketing Communities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Appt_No_Show_Cancel_Reason__c</fullName>
        <label>Appt No Show/Cancel Reason</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Loss_Reason__c</fullName>
        <label>Loss Reason</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>StageName</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Appraisal Issue</fullName>
                </value>
                <value>
                    <fullName>Changed Mind</fullName>
                </value>
                <value>
                    <fullName>Change in Employment / Relocation</fullName>
                </value>
                <value>
                    <fullName>Change in Marital Status</fullName>
                </value>
                <value>
                    <fullName>Concerns with Disclosure</fullName>
                </value>
                <value>
                    <fullName>Contingency Expiration</fullName>
                </value>
                <value>
                    <fullName>Correction</fullName>
                </value>
                <value>
                    <fullName>Customer Satisfaction</fullName>
                </value>
                <value>
                    <fullName>Discontinued Product</fullName>
                </value>
                <value>
                    <fullName>Homesite Conditions</fullName>
                </value>
                <value>
                    <fullName>Loan Denial</fullName>
                </value>
                <value>
                    <fullName>Lot Transfer / Lot Assignment</fullName>
                </value>
                <value>
                    <fullName>Material Out of Stock</fullName>
                </value>
                <value>
                    <fullName>Medical Reasons</fullName>
                </value>
                <value>
                    <fullName>Nonperformance</fullName>
                </value>
                <value>
                    <fullName>Offer Not Accepted</fullName>
                </value>
                <value>
                    <fullName>Purchased with Competitor</fullName>
                </value>
                <value>
                    <fullName>Right of Rescission</fullName>
                </value>
                <value>
                    <fullName>Unsatisfied with Product</fullName>
                </value>
                <value>
                    <fullName>.Cost Objections</fullName>
                </value>
                <value>
                    <fullName>.Just Looking</fullName>
                </value>
                <value>
                    <fullName>.No Response</fullName>
                </value>
                <value>
                    <fullName>.Not Interested</fullName>
                </value>
                <value>
                    <fullName>.Other Builder</fullName>
                </value>
                <value>
                    <fullName>.Out of Market</fullName>
                </value>
                <value>
                    <fullName>.Timeline</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Marketing_Community__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Marketing Community</label>
        <referenceTo>Marketing_Community__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opp_Cancel_Loss_Date__c</fullName>
        <label>Opp Cancel/Loss Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Sales_Office__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Sales Office</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Sales_Office__c.Is_Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Sales_Office__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Sales_Agent__c.object
<CustomObject>
    <fields>
        <fullName>Related_to_User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Related to User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Sales_Agents</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Sales Agent</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Agents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Sales_Office__c.object
<CustomObject>
    <description>NEWSTAR Sales Office</description>
    <label>Sales Office</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Offices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/SalesAgentSalesOfficeLink__c.object
<CustomObject>
    <fields>
        <fullName>Is_Primary__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Primary</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Sales_Agent__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Sales Agent</label>
        <referenceTo>Sales_Agent__c</referenceTo>
        <relationshipLabel>Sales Agent Sales Office Relationships</relationshipLabel>
        <relationshipName>Sales_Agent_Sales_Office_Relationships</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sales_Office__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Sales Office</label>
        <referenceTo>Sales_Office__c</referenceTo>
        <relationshipLabel>Sales Agent Sales Office Relationships</relationshipLabel>
        <relationshipName>Sales_Agent_Sales_Office_Relationships</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Sales Agent Sales Office Relationship</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Agent Sales Office Relationships</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/BRPvalidation.cls
public without sharing class BRPvalidation
{
   
   public void genericInterestcreation( sobject s,string actiontype,string val, string activelistfieldname, string historylistfieldname  )
   {
      list<string> lstcommunity=new list<string>();
      list<string> lstcommunityHist=new list<string>();
      string activevalue=(string)s.get(activelistfieldname);
      string historyvalue=(string)s.get(historylistfieldname);
      system.debug(activevalue);
      system.debug(historyvalue);
      if(activevalue!=null)
          lstcommunity = activevalue.split(';');
      if(historyvalue!=null)
          lstcommunityHist = historyvalue.split(';');
      if(lstcommunity.size()>0)
          {
              if(actiontype=='Insert')
                   {
                       if(lstCommunity.contains(val)==false)
                          s.put(activelistfieldname, activevalue + ';' + val);
                   }
              else if(actiontype=='Delete')
                   {
                       lstcommunity.remove(lstCommunity.indexOf(val));
                       string newlist='';
                       for(integer i=0;i<lstcommunity.size();i++)
                       newlist = newlist + ';' + lstcommunity[i];
                       s.put(activelistfieldname,newlist);                                 
                   }

           }
       else
           {
               if(actiontype=='Insert')
                   s.put(activelistfieldname, val);

           }
                          
       if(lstcommunityHist.size()>0)
           {
               if(actiontype=='Insert')
                   {
                        if(lstcommunityHist.contains(val)==false)
                             s.put(historylistfieldname  , historyvalue + ';' + val);
                   }
           }
        else
           {
               if(actiontype=='Insert')
                         s.put(historylistfieldname, val);

           }
      
   }
   public static string getsalesofficename(sobject s)
    {
        string sname=(string) s.get('sales_office_mapping__c');
        BRPSalesSettings__c soffname= BRPSalesSettings__c.getInstance(sname.split(' ')[0]);
        return soffname.Sales_Office_Name__c ;
    }
    public static string getsalesofficename(string sname)
    {
        //string sname=(string) s.get('sales_office_mapping__c');
        BRPSalesSettings__c soffname= BRPSalesSettings__c.getInstance(sname.split(' ')[0]);
        return soffname.Sales_Office_Name__c ;
    }
    public static String getSobjectNameById(Id inputId)
    {
        Schema.SObjectType sobjectType = inputId.getSObjectType();
        return sobjectType.getDescribe().getName();
    }
    public static string getHSFormUrl(string sname)
    {
        //string sname=(string) s.get('sales_office_mapping__c');
        BRPSalesSettings__c soffname= BRPSalesSettings__c.getInstance(sname.split(' ')[0]);
        return soffname.HsFormurl__c ;
    }
    public static boolean getSharingType(string sname)
    {
        //string sname=(string) s.get('sales_office_mapping__c');
        BRPSalesSettings__c soffname= BRPSalesSettings__c.getInstance(sname.split(' ')[0]);
        return soffname.SharingType__c   ;
    }
   /* public static void getGroup(Id oppId,List<string> mktcomm,string Accesslevel)
    {
           string query='select Id from Group where Type = \'Regular\' and ';
           for(integer i=0; i<mktcomm.size();i++)
           {
                if(mktcomm.size()==1)
                    query = query + ' Name like \'%' + String.escapeSingleQuotes(mktcomm[i])  +'%\'';
                else
                {  
                    if(i==0) 
                        query=query + '( Name like \'%' + String.escapeSingleQuotes(mktcomm[i])  +'%\'';
                    else if( i==mktcomm.size()-1)
                    {
                        query=query + ' or Name like \'%' + String.escapeSingleQuotes(mktcomm[i])  +'%\')';
                    }
                    else
                    {
                        query=query + ' or Name like \'%' + String.escapeSingleQuotes(mktcomm[i])  +'%\'';
                    }
                }
            }
           system.debug(query);
           list<Group> u =Database.query(query);
           OpportunitySharing.manualShareRead(oppId,u,AccessLevel);
    }*/
    public static string rollupOppstages(Id accountId)
    {
        string retstage='';
        List<Aggregateresult> groupedResults =[select stagename,count(ID) total from opportunity where accountid=: accountId group by stagename ];
        map<string,Integer> mpAccountoppostages=new map<String,Integer>();
        integer recordtotal=0;
        for (AggregateResult ar : groupedResults)  
        {
            mpAccountoppostages.put((string)ar.get('stagename'),(integer) ar.get('total'));
            recordtotal=recordtotal + (integer) ar.get('total');
        //    mpAccountoppostages.put(opp.Id,opp.StageName);
        }
        if(recordtotal == mpAccountoppostages.get('Prospecting'))
            retstage='Prospecting';
        else if(recordtotal == mpAccountoppostages.get('Cancelled'))
            retstage='Cancelled' + '~' + getCancelorLossreason(accountId,'Appt_No_Show_Cancel_Reason__c');
        else if(recordtotal == mpAccountoppostages.get('Lost'))
            retstage='Lost' + '~' + getCancelorLossreason(accountId,'Loss_Reason__c');
        else if(mpAccountoppostages.get('Closed Home')!=null)
            retstage='Closed Home';
        else if(mpAccountoppostages.get('Under Contract')!=null)
            retstage='Under Contract';
        else if(mpAccountoppostages.get('Pending Offer')!=null)
            retstage='Pending Offer';
        else if(mpAccountoppostages.get('Contract Ready')!=null)
            retstage='Contract Ready';
        else if(mpAccountoppostages.get('Lot Reservation')!=null)
            retstage='Lot Reservation';
        else if(mpAccountoppostages.get('Quote Closed')!=null)
            retstage='Quote Closed';
        else if(mpAccountoppostages.get('Quote/Selection')!=null)
            retstage='Quote/Selection';
        else if(mpAccountoppostages.get('Engagement')!=null)
            retstage='Engagement';
              
        return retstage;
    }
    private static string getCancelorLossreason(Id accountid,string fieldname )
    {
        string sqlQuery='Select ' + fieldname + ' from opportunity where accountid=: accountId order by Opp_Cancel_Loss_Date__c  desc limit 1';
        list<opportunity> lstopp=Database.query(sqlQuery);
        sobject s=lstopp[0];
        return (string)s.get(fieldname); 
    }
    public list<String> getOppSharingGroups(string Id)
    {
      list<string> lstshrgroups=new list<string> ();
      for(group g: [select Name from Group where Type = 'Regular' and Id  In (select userorgroupid from opportunityshare where opportunityid=:Id)])
          lstshrgroups.add(g.Name);
      return lstshrgroups;
    }
  private static list<string> getcommunitynames(string sofficename,string commname)
  {
     list<string> lstcommunityname=new list<string>();
     list<string>lstsecondlist=new list<string>();
     //system.debug(sofficename);
     //string nameval=BRPValidation.getsalesofficename(sofficename);
     List<List<string>> lstarrayCommunityname= quickLeadCreate.getPicklistvalues('account','community_picklist_' + sofficename +'__pc',false);
     for(integer i=0;i<lstarrayCommunityname.size();i++)
     {
         lstcommunityname.addall(lstarrayCommunityname[i]);
     }
     for(integer i=0;i<lstcommunityname.size();i++)
     {
         if(lstcommunityname[i] !=commname)
             lstsecondlist.add(lstcommunityname[i]);
     }
     return lstsecondlist;
  }
  public void ShareOppwithcommunity(list<Opportunity> lstopp)
  {
       
      // Sales team Group owning the community being added to opportunity share
               //list<string> lstprimarycommname=new list<string>();
               //lstprimarycommname.add(mktcomm);
         Map<Id,string> mpmktcomm=new Cachedcollections().getCachecommunityMapIds;
         map<string,Marketing_community__c> mpmktcommobj=new Cachedcollections().getCachecommunityMapNames;
         map<string,group> mpgroup=new Cachedcollections().getGroup;
         map<Id,list<Group>> mpoppuserOrGroupId=new map<Id,list<Group>>();
         for(opportunity opp:lstopp)
         {
               
               string mktcomm=mpmktcomm.get(opp.Marketing_Community__c);
               Marketing_community__c mktcommobj=mpmktcommobj.get(mktcomm);
               
               list<group> lstgroup=new list<group>();
               if(mpgroup.get(mktcomm)!=null)
               {
                   lstgroup.add(mpgroup.get(mktcomm));
                   mpoppuserOrGroupId.put(opp.Id,lstgroup);
               }
               //system.debug('Add opportunityshare for group owner');
              /* string soffname=BRPValidation.getsalesofficename(mktcommobj.sales_office__r.Name);
               if(brpValidation.getSharingType(mktcommobj.sales_office__r.Name)==true)
               {
                   if(mktcommobj.Other_groups_can_Read__c==true)
                   {
                       // system.debug('Add opportunityshare for others');
                        list<string> lstcommunityname=getcommunitynames(soffname,mktcomm);
                        list<group> u=new list<group>();
                        for(string s:lstcommunityname)
                        {
                            if(mpgroup.get(s)!=null)
                                u.add(mpgroup.get(s));
                        }
                        //BRPValidation.getGroup(oppId,lstcommunityname,'Read');
                        OpportunitySharing.manualShareRead(opp.Id,u,'Read');
                   }
               }*/
         }
         OpportunitySharing.manualShareRead(mpoppuserOrGroupId,'Edit');
 
  }
  public void AssigntoISRgroup(list<Opportunity> lstopp)
  {
         try
         {
          //ISR for that salesoffice being added to opportunity share
         Map<Id,string> mpmktcomm=new Cachedcollections().getCachecommunityMapIds;
         map<string,Marketing_community__c> mpmktcommobj=new Cachedcollections().getCachecommunityMapNames;
         map<string,group> mpgroup=new Cachedcollections().getGroup;
         map<Id,list<Group>> mpoppuserOrGroupId=new map<Id,list<Group>>();
         for(opportunity opp:lstopp)
         {
              string mktcomm=mpmktcomm.get(opp.Marketing_Community__c);
              Marketing_community__c mktcommobj=mpmktcommobj.get(mktcomm);
              string soffname=BRPValidation.getsalesofficename(mktcommobj.sales_office__r.Name);
              //list<string> lstsalesoffname=new list<string>();
          //lstsalesoffname.add(soffname);
              list<group> lstcommunitysalesname=new list<group>();
              system.debug(mpgroup);
              if(mpgroup.get(soffname + ' Online Sales')!=null)
              {
                   lstcommunitysalesname.add(mpgroup.get(soffname + ' Online Sales'));
                   mpoppuserOrGroupId.put(opp.Id,lstcommunitysalesname);
              }
              
          }
          OpportunitySharing.manualShareRead(mpoppuserOrGroupId,'Edit');
          }
          catch(exception ex)
          {
              system.debug(ex.getmessage());
          }
       
          //BRPValidation.getGroup(oppId,lstsalesoffname,'Edit');
  }

  public string getProfileName(string userId)
  {
      string retvalue='';
      for(user u :[SELECT Id,profile.Name From User where id =: userId limit 1])
      {
          retvalue=u.profile.name;
      }
      return retvalue;
  }
  public string getSalesAgentOfficeId(string UserId)
  {
      string retvalue='';
      for(SalesAgentSalesOfficeLink__c sagent :[SELECT Id From SalesAgentSalesOfficeLink__c where Sales_Agent__r.Related_to_User__c  =: userId and is_primary__c=true limit 1])
      {
          retvalue=sagent.Id;
      }
      return retvalue;
  }
}