objects/BeBack__c.object
<CustomObject>
    <fields>
        <fullName>Is_Be_Back__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Be Back</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Notes_Added_by__c</fullName>
        <defaultValue>$User.FirstName + ' ' + $User.LastName</defaultValue>
        <label>Notes Added by</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Notes__c</fullName>
        <label>Notes</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Visit_Date__c</fullName>
        <label>Entry Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Prospect Notes</relationshipLabel>
        <relationshipName>Prospect_Notes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Prospect Note</label>
    <nameField>
        <label>Prospect Note</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Prospect Notes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Marketing_Community__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Marketing Community</label>
        <referenceTo>Marketing_Community__c</referenceTo>
        <relationshipLabel>Leads</relationshipLabel>
        <relationshipName>Leads</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Visit_Date__c</fullName>
        <label>Date of First Visit</label>
        <type>Date</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

objects/Marketing_Community__c.object
<CustomObject>
    <description>SiteCore/CMS "marketing community"</description>
    <label>Marketing Community</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Marketing Communities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Marketing_Community__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Marketing Community</label>
        <referenceTo>Marketing_Community__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Visit_Date__c</fullName>
        <label>Date of First Visit</label>
        <type>Date</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/Notessummary.cls
public inherited sharing class Notessummary
{
    public lead leadObj{get; set;} 
    public account acctobj{get;set;}
    public string notes{get; set;}
    public Notessummary(ApexPages.StandardController controller) 
    {
      this.notes='';
      String type = controller.getRecord().getSObjectType().getDescribe().getName();
      if(type=='Account')
          this.acctobj = (Account)Controller.getRecord();
     this.notes=Getnotes(type,acctobj.Id);
    }
    public Notessummary() 
    {
     
    }
    public static string Getnotes(string type,string accId)
    {
        list<beBack__c> prospectnotes;
        if(type=='Account')
            prospectnotes=[select notes__c,visit_date__c,name, is_be_back__c, opportunity__c,opportunity__r.marketing_community__r.Name,Notes_Added_by__c
            from beback__c where  opportunity__c in
            (select id from opportunity where accountid =: accId) order by visit_date__c desc];
        system.debug(prospectnotes);
        string note='';
        for(beback__c n: prospectnotes)
        {            //system.debug(n.Community_of_Interest__r.marketing_community__r.Name);
            Date dt=n.Visit_date__c;
            string beback=': Is Be back';
            if(n.is_be_back__c==true)
             {
                 if(type=='Account')
                      note=note+ dt.day() + '-'+ dt.Month() + '-' + dt.year() + beback +'</br>' + 'Project: '
                    + n.opportunity__r.marketing_community__r.Name +'</br>'
                    + n.Notes_Added_by__c  + ': ' + n.notes__c + '</p>';
             }
                 
            else 
              {  
                 system.debug('hello');
                 if(type=='Account')
                     note=note+ dt.day() + '-'+ dt.Month() + '-' +dt.year() +'</br>' 
                     + 'Project: ' + n.opportunity__r.marketing_community__r.Name +'</br>'
                     + n.Notes_Added_by__c  + ': ' + n.notes__c + '</p>';
               }
                 
           
        }
       system.debug(note);
       return note;
    }
}