objects/BRPSalesSettings__c.object
<CustomObject>
    <fields>
        <fullName>Sales_Office_Name__c</fullName>
        <label>Sales Office Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <customSettingsType>List</customSettingsType>
    <label>BRP Sales Settings</label>
</CustomObject>

objects/Marketing_Community__c.object
<CustomObject>
    <fields>
        <fullName>Other_groups_can_Read__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Other groups can Read?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Sales_Process_Type__c</fullName>
        <defaultValue>'Direct offer'</defaultValue>
        <label>Default Sales Process Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Direct offer</fullName>
                </value>
                <value>
                    <fullName>Lot reservation</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Sales_office__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sales Office</label>
        <referenceTo>Sales_Office__c</referenceTo>
        <relationshipLabel>Marketing Communities</relationshipLabel>
        <relationshipName>Marketing_Communities</relationshipName>
        <type>Lookup</type>
    </fields>
    <description>SiteCore/CMS "marketing community"</description>
    <label>Marketing Community</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Marketing Communities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Sales_Agent__c.object
<CustomObject>
    <fields>
        <fullName>First_Name__c</fullName>
        <label>First Name</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Related_to_User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Related to User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Sales_Agents</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Sales Agent</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Agents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Sales_Office__c.object
<CustomObject>
    <description>NEWSTAR Sales Office</description>
    <label>Sales Office</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Offices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/SalesAgentSalesOfficeLink__c.object
<CustomObject>
    <fields>
        <fullName>Is_Primary__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Primary</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Sales_Agent__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Sales Agent</label>
        <referenceTo>Sales_Agent__c</referenceTo>
        <relationshipLabel>Sales Agent Sales Office Relationships</relationshipLabel>
        <relationshipName>Sales_Agent_Sales_Office_Relationships</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sales_Office__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Sales Office</label>
        <referenceTo>Sales_Office__c</referenceTo>
        <relationshipLabel>Sales Agent Sales Office Relationships</relationshipLabel>
        <relationshipName>Sales_Agent_Sales_Office_Relationships</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Sales Agent Sales Office Relationship</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Agent Sales Office Relationships</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/TestDataFactoryforHS.cls
@isTest 
public class TestDataFactoryforHS 
{ 
    public static user createISRUser()
    { 
        String uniqueUserName = 'standarduser' + DateTime.now().getTime() + '@testorg.com'; 
        Profile p = [SELECT Id FROM Profile WHERE Name='DC ISR profile']; 
               
        User u = new User(Alias = 'standt', Email='standarduser@testorg.com', 
        EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
        LocaleSidKey='en_US', ProfileId = p.Id, 
        TimeZoneSidKey='America/Los_Angeles', 
        UserName=uniqueUserName); 
        insert u;
        return u;
    } 
    public static user createSalesUser()
    { 
        String uniqueUserName = 'standarduser' + DateTime.now().getTime() + '@testorg.com'; 
        Profile p = [SELECT Id FROM Profile WHERE Name='DC Sales User profile']; 

        User u = new User(Alias = 'standt2', Email='standarduser2@testorg.com', 
        EmailEncodingKey='UTF-8', LastName='Testing2', LanguageLocaleKey='en_US', 
        LocaleSidKey='en_US', ProfileId = p.Id, 
        TimeZoneSidKey='America/Los_Angeles', 
        UserName=uniqueUserName+'.ver2'); 
        insert u;
        return u;
    } 
    
    public static BRPSalesSettings__c  CreateCustomSetting()
    {
        BRPSalesSettings__c csobj=new BRPSalesSettings__c (); 
        csobj.Sales_Office_Name__c='Wash'; 
        csobj.name='Washington'; 
        insert csobj;
        return csobj;
    }
    
    public static Sales_Office__c  CreateSalesOffice(string soffname)
    {
        Sales_Office__c soffice=new Sales_Office__c(name=soffname);
        insert soffice;
        return soffice;
    }
    public static Marketing_community__c CreateMarketingcommunity(string mktname,Id SofficeId)
    {
        Marketing_community__c mktcomm=new  Marketing_community__c(name=mktname,Sales_office__c=SofficeId,Sales_Process_Type__c='Lot reservation',Other_groups_can_Read__c=false);
        insert mktcomm;
        return mktcomm;
    }
    public static SalesAgentSalesOfficeLink__c  Createsalesagentlink(string fname, string lname, Id userid,ID sofficeId)
    {
        //ISR user sales agent
        sales_agent__c sagent= new sales_agent__c(First_name__c=fname,last_name__c=lname, Related_to_User__c=userid);
        insert sagent;
        SalesAgentSalesOfficeLink__c sofficeagent= new SalesAgentSalesOfficeLink__c(Name=fname + ' ' + lname, Sales_Office__c=sofficeId,
        Is_Primary__c=true,Sales_Agent__c=sagent.Id);
        insert sofficeagent;
        return sofficeagent;
    }
}