objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Age_Group__c</fullName>
        <label>Age Group</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>20-29</fullName>
                </value>
                <value>
                    <fullName>30-39</fullName>
                </value>
                <value>
                    <fullName>40-49</fullName>
                </value>
                <value>
                    <fullName>50-59</fullName>
                </value>
                <value>
                    <fullName>60-69</fullName>
                </value>
                <value>
                    <fullName>70+</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Are_you_transferring_to_the_area__c</fullName>
        <inlineHelpText>If transferring to the area, enter transfer date.</inlineHelpText>
        <label>Are you transferring to the area?</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Area_of_Interest__c</fullName>
        <inlineHelpText>Select all areas of interest</inlineHelpText>
        <label>Area of Interest</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Cedar Park / Leander</fullName>
                </value>
                <value>
                    <fullName>Central &amp; East Austin</fullName>
                </value>
                <value>
                    <fullName>Dripping Springs</fullName>
                </value>
                <value>
                    <fullName>Georgetown / Liberty Hill</fullName>
                </value>
                <value>
                    <fullName>Lakeway / Bee Cave</fullName>
                </value>
                <value>
                    <fullName>San Marcos</fullName>
                </value>
                <value>
                    <fullName>No Preference</fullName>
                </value>
                <value>
                    <fullName>Ann Arundel</fullName>
                </value>
                <value>
                    <fullName>Fairfax</fullName>
                </value>
                <value>
                    <fullName>Frederick</fullName>
                </value>
                <value>
                    <fullName>Loudoun</fullName>
                </value>
                <value>
                    <fullName>Montgomery</fullName>
                </value>
                <value>
                    <fullName>Prince William</fullName>
                </value>
                <value>
                    <fullName>Sussex</fullName>
                </value>
                <value>
                    <fullName>Talbot</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Bathrooms__c</fullName>
        <label>Bathrooms</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>2.5</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                </value>
                <value>
                    <fullName>3.5</fullName>
                </value>
                <value>
                    <fullName>4</fullName>
                </value>
                <value>
                    <fullName>4+</fullName>
                </value>
                <value>
                    <fullName>5</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Bedrooms__c</fullName>
        <label>Bedrooms</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                </value>
                <value>
                    <fullName>4</fullName>
                </value>
                <value>
                    <fullName>5</fullName>
                </value>
                <value>
                    <fullName>5+</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Consent_to_Follow_Up__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Consent to Follow Up</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Do_you_currently_own_or_rent__c</fullName>
        <label>Do you currently own or rent?</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Own</fullName>
                </value>
                <value>
                    <fullName>Rent</fullName>
                </value>
                <value>
                    <fullName>None</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Household_Income__c</fullName>
        <label>Household Income</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Under $50,000</fullName>
                </value>
                <value>
                    <fullName>$50,000 - $74,999</fullName>
                </value>
                <value>
                    <fullName>$75,000 - $99,999</fullName>
                </value>
                <value>
                    <fullName>$100,000 - $149,999</fullName>
                </value>
                <value>
                    <fullName>$150,000 - $199,999</fullName>
                </value>
                <value>
                    <fullName>$200,000 - $299,999</fullName>
                </value>
                <value>
                    <fullName>$300,000 - $399,999</fullName>
                </value>
                <value>
                    <fullName>$400,000 - $499,999</fullName>
                </value>
                <value>
                    <fullName>$500,000 Plus</fullName>
                </value>
                <value>
                    <fullName>$35,000 - $49,999</fullName>
                    <isActive>false</isActive>
                    <label>$35,000 - $49,999</label>
                </value>
                <value>
                    <fullName>$400,000+</fullName>
                    <isActive>false</isActive>
                    <label>$400,000+</label>
                </value>
                <value>
                    <fullName>Up to $34,999</fullName>
                    <isActive>false</isActive>
                    <label>Up to $34,999</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>How_long_have_you_been_house_hunting__c</fullName>
        <label>How long have you been house hunting?</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Less than 1 Month</fullName>
                </value>
                <value>
                    <fullName>1-3 Months</fullName>
                </value>
                <value>
                    <fullName>3-6 Months</fullName>
                </value>
                <value>
                    <fullName>6+ Months</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Is_Web_Lead__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Web Lead</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Lead_Channel__c</fullName>
        <label>Lead Channel</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Lead_Channel</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Lead_Source_Detail__c</fullName>
        <label>Lead Source Detail</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>MaritalStatus__c</fullName>
        <defaultValue>false</defaultValue>
        <label>MaritalStatus</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Number_of_Children_in_Home__c</fullName>
        <label>Number of Children in Home</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>0</fullName>
                </value>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                </value>
                <value>
                    <fullName>4+</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Realtor__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Are You a Realtor?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Sales_Office__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Sales Office</label>
        <referenceTo>Sales_Office__c</referenceTo>
        <relationshipLabel>Leads</relationshipLabel>
        <relationshipName>Leads</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sales_office_mapping__c</fullName>
        <label>Sales office mapping</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Transferring_to_area_date__c</fullName>
        <inlineHelpText>If lead is transferring to the area, enter date they expect to transfer.</inlineHelpText>
        <label>Transferring to area date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Visit_Brookfield_website_during_search__c</fullName>
        <label>Visit Brookfield website during search?</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Visit_Date__c</fullName>
        <label>Date of First Visit</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>What_is_your_price_range__c</fullName>
        <inlineHelpText>Legacy TX Lead field for Marketing purposes</inlineHelpText>
        <label>What is your price range?</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>under $250,000</fullName>
                </value>
                <value>
                    <fullName>$250,000 - $299,999</fullName>
                </value>
                <value>
                    <fullName>$300,000 - $349,999</fullName>
                </value>
                <value>
                    <fullName>$350,000 - $399,999</fullName>
                </value>
                <value>
                    <fullName>$400,000 - $499,999</fullName>
                </value>
                <value>
                    <fullName>$500,000 - $599,999</fullName>
                </value>
                <value>
                    <fullName>$600,000 - $699,999</fullName>
                </value>
                <value>
                    <fullName>$700,000 - $849,999</fullName>
                </value>
                <value>
                    <fullName>$850,000 - $999,999</fullName>
                </value>
                <value>
                    <fullName>$1,000,000 - $1,999,999</fullName>
                </value>
                <value>
                    <fullName>Over $2,000,000</fullName>
                </value>
                <value>
                    <fullName>$100,000 - $149,999</fullName>
                    <isActive>false</isActive>
                    <label>$100,000 - $149,999</label>
                </value>
                <value>
                    <fullName>$150,000 - $199,999</fullName>
                    <isActive>false</isActive>
                    <label>$150,000 - $199,999</label>
                </value>
                <value>
                    <fullName>$200,000 - $249,999</fullName>
                    <isActive>false</isActive>
                    <label>$200,000 - $249,999</label>
                </value>
                <value>
                    <fullName>$500,000 - $700,000</fullName>
                    <isActive>false</isActive>
                    <label>$500,000 - $700,000</label>
                </value>
                <value>
                    <fullName>Over $700,000</fullName>
                    <isActive>false</isActive>
                    <label>Over $700,000</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

objects/SalesAgentSalesOfficeLink__c.object
<CustomObject>
    <fields>
        <fullName>Sales_Office__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Sales Office</label>
        <referenceTo>Sales_Office__c</referenceTo>
        <relationshipLabel>Sales Agent Sales Office Relationships</relationshipLabel>
        <relationshipName>Sales_Agent_Sales_Office_Relationships</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Sales Agent Sales Office Relationship</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Agent Sales Office Relationships</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

globalValueSets/Lead_Channel.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Walk-in</fullName>
    </customValue>
    <customValue>
        <fullName>Phone Inquiry</fullName>
        <label>Phone Inquiry - Onsite</label>
    </customValue>
    <customValue>
        <fullName>Phone Inquiry - Online</fullName>
    </customValue>
    <customValue>
        <fullName>Online</fullName>
    </customValue>
    <customValue>
        <fullName>Event Registration/Import</fullName>
    </customValue>
    <customValue>
        <fullName>MyTime Tour</fullName>
    </customValue>
    <masterLabel>Lead Channel</masterLabel>
</GlobalValueSet>

classes/Hubspotcreationcalls.cls
public class Hubspotcreationcalls
{
   public static string createHsformdata(lead leadobj,string selectcommunity) 
   {
       string formdata='';
       
       formdata=formdata +'firstname=' + EncodingUtil.urlEncode(leadobj.firstname,'utf-8');
       formdata=formdata +'&lastname=' + EncodingUtil.urlEncode(leadobj.lastname,'utf-8');
       formdata=formdata +'&email=' + EncodingUtil.urlEncode(leadobj.email,'utf-8');
       formdata=formdata +'&mobile_phone =' + EncodingUtil.urlEncode(leadobj.MobilePhone,'utf-8');
       formdata=formdata +'&phone=' + EncodingUtil.urlEncode(leadobj.Phone,'utf-8');

       formdata=formdata +'&realtor__c=' + leadobj.realtor__c;
       formdata=formdata +'&maritalstatus__c=' + leadobj.maritalstatus__c;
       formdata=formdata +'&hs_email_optout=' + !(leadobj.Consent_to_Follow_Up__c);
       formdata=formdata +'&consent_to_follow_up =' + leadobj.Consent_to_Follow_Up__c;
       list<SalesAgentSalesOfficeLink__c> lstsalesoffice=quickLeadCreate.getSalesOffices(userInfo.getUserId());
       string salesoffice= lstsalesoffice[0].Sales_Office__r.Name;
       sobject s =(sobject) leadobj;
       if(leadobj.realtor__c == false)
       {
           string salesofficeId= lstsalesoffice[0].Sales_Office__r.Id;
           formdata=formdata +'&sales_office_mapping__c=' + EncodingUtil.urlEncode(salesoffice,'utf-8');
           formdata=formdata +'&salesoffice =' + EncodingUtil.urlEncode(salesofficeId,'utf-8');
           //formdata=formdata +'&salesoffice =' + EncodingUtil.urlEncode(salesofficeId,'utf-8');project__c 
           string nameval=BRPValidation.getsalesofficename(salesoffice);
           string communityfieldname='community_picklist_'+ nameval;
           system.debug(communityfieldname);
           system.debug(selectcommunity);
           formdata=formdata +'&' + communityfieldname.toLowerCase() + '=' + EncodingUtil.urlEncode(selectcommunity,'utf-8');
       }
        if(leadobj.Visit_Date__c!=null)
       {
           Datetime dt=leadobj.visit_date__c;
           string d=dt.formatGMT('yyyy-MM-dd');
           system.debug('visit_date__c: ' + d);
           formdata=formdata +'&visit_date__c=' + d ;
       }
       if(leadobj.lead_channel__c!='')
           formdata=formdata +'&lead_channel__c=' + EncodingUtil.urlEncode(leadobj.lead_channel__c ,'utf-8');
       if(leadobj.LeadSource!='')
           formdata=formdata +'&leadsource=' + EncodingUtil.urlEncode(leadobj.leadsource,'utf-8');
       if(leadobj.lead_source_detail__c!='')
           formdata=formdata +'&lead_source_detail__c=' + EncodingUtil.urlEncode(leadobj.lead_source_detail__c,'utf-8');
       if(leadobj.area_of_interest__c!='')
           formdata=formdata +'&area_of_interest__c=' + EncodingUtil.urlEncode(leadobj.area_of_interest__c,'utf-8');
       
       if(leadobj.age_group__c!='')
           formdata=formdata +'&age_group__c=' + EncodingUtil.urlEncode(leadobj.age_group__c,'utf-8');

       if(leadobj.do_you_currently_own_or_rent__c!='')
           formdata=formdata +'&do_you_currently_own_or_rent__c=' + EncodingUtil.urlEncode(leadobj.do_you_currently_own_or_rent__c,'utf-8');
       if(leadobj.are_you_transferring_to_the_area__c!='')
           formdata=formdata +'&are_you_transferring_to_the_area__c=' + EncodingUtil.urlEncode(leadobj.are_you_transferring_to_the_area__c,'utf-8');
        if(leadobj.transferring_to_area_date__c!=null)
       {
           Datetime dt=leadobj.transferring_to_area_date__c;
           string d=dT.format('yyyy-MM-dd');
           formdata=formdata +'&transferring_to_area_date__c=' + d;
       }
       if(leadobj.how_long_have_you_been_house_hunting__c!='')
           formdata=formdata +'&how_long_have_you_been_house_hunting__c=' + EncodingUtil.urlEncode(leadobj.how_long_have_you_been_house_hunting__c,'utf-8');
       if(leadobj.visit_brookfield_website_during_search__c!='')
           formdata=formdata +'&visit_brookfield_website_during_search__c=' + EncodingUtil.urlEncode(leadobj.visit_brookfield_website_during_search__c,'utf-8');
       if(leadobj.household_income__c!='')
           formdata=formdata +'&household_income__c=' + EncodingUtil.urlEncode(leadobj.household_income__c,'utf-8');
       if(leadobj.what_is_your_price_range__c !='')
           formdata=formdata +'&what_is_your_price_range__c =' + EncodingUtil.urlEncode(leadobj.what_is_your_price_range__c ,'utf-8');
       if(leadobj.bedrooms__c!='')
           formdata=formdata +'&bedrooms__c=' + EncodingUtil.urlEncode(leadobj.bedrooms__c,'utf-8');
       if(leadobj.bathrooms__c!='')
           formdata=formdata +'&bathrooms__c=' + EncodingUtil.urlEncode(leadobj.bathrooms__c,'utf-8');
       if(leadobj.Number_of_Children_in_Home__c!='')
           formdata=formdata +'&number_of_children_in_home__c =' + EncodingUtil.urlEncode(leadobj.Number_of_Children_in_Home__c,'utf-8');   
       formdata=formdata +'&Is_Web_Lead__c=' + leadobj.Is_Web_Lead__c;
       formdata=formdata +'&sessionid=' + EncodingUtil.urlEncode(userInfo.getSessionId(),'utf-8'); 
       formdata=formdata +'&createduser=' + EncodingUtil.urlEncode(userInfo.getUserId(),'utf-8'); 
       
       
       
       JSONGenerator pc= JSON.createGenerator(true);
       pc.writeStartObject();
       pc.writeStringField('hutk','76cb4fcc-1514-444a-b627-5714574482b0');
       pc.writeEndObject();
       string body= pc.getAsString();
       formdata=formdata + '&hs_context=' + body;
       system.debug(formdata);
       string url='https://forms.hubspot.com/uploads/form/v2/'+ BRPValidation.getHSFormUrl(salesoffice);
       system.debug('pc: ' + pc);
       HttpRequest req = new HttpRequest();
       req.setEndpoint(url);
       req.setMethod('POST');
        //req.setHeader('Content-Type', 'application/json');
       req.setHeader('Content-Type', 'application/x-www-form-urlencoded');
        
       req.setBody(formdata); 
       Http http = new Http(); 
          try
            {

            HTTPResponse res = http.send(req);
            Integer retCode = res.getStatusCode();
            if(retCode != 204)
            {
                //s.put('Sales_office_mapping__c',salesoffice);
                //s.put(communityfieldname +'__c',selectcommunity);
                //s.put('sessionId__c',userinfo.getsessionId());
                //lead ld=(lead) s;
                //insert ld;
            }
            String retMsg = res.getStatus();
            }
            catch(exception ex)
            {
            }
      return userInfo.getSessionId();
   }      
}