objects/Lot__c.object
<CustomObject>
    <fields>
        <fullName>Base_Model_Price_Override__c</fullName>
        <label>Base Model Price Override</label>
        <precision>11</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Preconfigured_Options_Amount__c</fullName>
        <label>Preconfigured Options Amount</label>
        <precision>11</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Premium__c</fullName>
        <label>Premium</label>
        <precision>11</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Price__c</fullName>
        <label>Price</label>
        <precision>11</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Subdivision__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Subdivision</label>
        <referenceTo>Subdivision__c</referenceTo>
        <relationshipLabel>Lots</relationshipLabel>
        <relationshipName>Lots</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Lot</label>
    <nameField>
        <label>Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Lots</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Marketing_Community__c.object
<CustomObject>
    <fields>
        <fullName>Sales_Process_Type__c</fullName>
        <defaultValue>'Direct offer'</defaultValue>
        <label>Default Sales Process Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Direct offer</fullName>
                </value>
                <value>
                    <fullName>Lot reservation</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <description>SiteCore/CMS "marketing community"</description>
    <label>Marketing Community</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Marketing Communities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Model__c.object
<CustomObject>
    <fields>
        <fullName>Price__c</fullName>
        <label>Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Subdivision__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Subdivision</label>
        <referenceTo>Subdivision__c</referenceTo>
        <relationshipLabel>Models</relationshipLabel>
        <relationshipName>Models</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Model</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Models</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Base_Model_Price__c</fullName>
        <label>Base Model Price</label>
        <precision>11</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Lot_Premium__c</fullName>
        <label>Lot Premium</label>
        <precision>11</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Lot_Price__c</fullName>
        <label>Lot Price</label>
        <precision>11</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Lot__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Lot</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>(1 AND 2 AND 3 AND 4) OR 5</booleanFilter>
            <errorMessage>Lot must belong to the selected subdivision, be available (open) and be released for sale.</errorMessage>
            <filterItems>
                <field>Lot__c.Subdivision__c</field>
                <operation>equals</operation>
                <valueField>$Source.Subdivision__c</valueField>
            </filterItems>
            <filterItems>
                <field>Lot__c.Released_for_Sale__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <filterItems>
                <field>Lot__c.Status__c</field>
                <operation>equals</operation>
                <value>Open</value>
            </filterItems>
            <filterItems>
                <field>$Source.StageName</field>
                <operation>equals</operation>
                <value>Prospecting, Engagement, Quote/Selection</value>
            </filterItems>
            <filterItems>
                <field>$Source.StageName</field>
                <operation>equals</operation>
                <value>Contract Ready, Lot Reservation, Pending Offer, Under Contract, Closed Home, Cancelled, Quote Closed</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Lot__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Marketing_Community__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Marketing Community</label>
        <referenceTo>Marketing_Community__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Model__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Model</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Model must belong to the selected subdivision and must be active.</errorMessage>
            <filterItems>
                <field>Model__c.Subdivision__c</field>
                <operation>equals</operation>
                <valueField>$Source.Subdivision__c</valueField>
            </filterItems>
            <filterItems>
                <field>Model__c.Is_Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Model__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Scenario_Name__c</fullName>
        <label>Scenario Name</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Subdivision__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Project</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Subdivision must belong to the selected sales office and the selected marketing community.</errorMessage>
            <filterItems>
                <field>Subdivision__c.Sales_Office__c</field>
                <operation>equals</operation>
                <valueField>$Source.Sales_Office__c</valueField>
            </filterItems>
            <filterItems>
                <field>Subdivision__c.Marketing_Community__c</field>
                <operation>equals</operation>
                <valueField>$Source.Marketing_Community__c</valueField>
            </filterItems>
            <infoMessage>Select a subdivision</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Subdivision__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Total_Actual_Sale_Amount__c</fullName>
        <label>Total Actual Sale Amount</label>
        <precision>11</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Total_Deposit_Due__c</fullName>
        <label>Total Deposit Due</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Total_Discount_Amount__c</fullName>
        <label>Total Discount Amount</label>
        <precision>11</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Total_Mortgage_Incentive_Included__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Total Mortgage Incentive Included</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Total_Mortgage_Incentive__c</fullName>
        <label>Total Mortgage Incentive</label>
        <precision>11</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Total_Options_Amount__c</fullName>
        <label>Total Options Amount</label>
        <precision>11</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Total_Proj_Mortg_Incent_Incl__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Total Projected Mortgage Incentive Incl.</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Total_Projected_Discount_Amount__c</fullName>
        <label>Total Projected Discount Amount</label>
        <precision>11</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Total_Projected_Mortgage_Incentive__c</fullName>
        <label>Total Projected Mortgage Incentive</label>
        <precision>11</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Total_Projected_Options_Amount__c</fullName>
        <label>Total Projected Options Amount</label>
        <precision>11</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Total_Projected_Sale_Amount__c</fullName>
        <label>Total Projected Sale Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Total_Projected_Tax_Amount__c</fullName>
        <label>Total Projected Tax Amount</label>
        <precision>11</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Total_Projected_Tax_Rebate_Amount__c</fullName>
        <label>Total Projected Tax Rebate Amount</label>
        <precision>11</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Total_Received_Deposit__c</fullName>
        <label>Total Received Deposit</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Total_Scheduled_Deposit__c</fullName>
        <label>Total Scheduled Deposit</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Total_Tax_Amount__c</fullName>
        <label>Total Tax Amount</label>
        <precision>11</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Total_Tax_Rebate_Amount__c</fullName>
        <label>Total Tax Rebate Amount</label>
        <precision>11</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Subdivision__c.object
<CustomObject>
    <fields>
        <fullName>Marketing_Community__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Marketing Community</label>
        <referenceTo>Marketing_Community__c</referenceTo>
        <relationshipLabel>Subdivisions</relationshipLabel>
        <relationshipName>Subdivisions</relationshipName>
        <type>Lookup</type>
    </fields>
    <description>NEWSTAR Sales Subdivision</description>
    <label>Project</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/NewstarOpporunityInfoService.cls
public with sharing class NewstarOpporunityInfoService {

    public static void setOpportunityNameAtMarketingCommunityLevel(Opportunity opp, NewstarDealContext dealContext)
    {
        
        if(dealContext==null) {
            dealContext=getDealContext(opp);
        }

        if(dealContext.MarketingCommunity!=null) {
            opp.Name=dealContext.CustomerAccount.Name + ' -  ' + dealContext.MarketingCommunity.Name+' - '+opp.Scenario_Name__c;
  
        } 
    }


    public static void setOpportunitySalesProcess(Opportunity opp, NewstarDealContext dealContext) {
        //assign the correct opportunity record type based on the sales process type picklist value configured on the marketing community
        String oppRecordTypeId=Schema.SObjectType.Opportunity.getRecordTypeInfosByName()
                .get(dealContext.MarketingCommunity.Sales_Process_Type__c)
                .getRecordTypeId();

        opp.RecordTypeId=oppRecordTypeId;
    }


    public static void setOpportunityNameAtSubdivisionLevel(Opportunity opp, NewstarDealContext dealContext)
    {
        
        if(dealContext==null) {
            dealContext=getDealContext(opp);
        }

        //set subdivision and lot in the opportunity name, if available
        if(dealContext.Subdivision!=null && dealContext.Lot!=null) {
             opp.Name= dealContext.CustomerAccount.Name + ' -  ' + dealContext.Subdivision.Name +' - Lot '+ dealContext.Lot.Name + ' - '+opp.Scenario_Name__c;
        } 
    }


    public static void setOpportunityAmountsFromDealContext(Opportunity opp, NewstarDealContext dealContext) {

       NewstarDealFinancialInfo financialInfo=new NewstarDealFinancialInfo();
      
       if(dealContext==null) {
            dealContext=getDealContext(opp);
        }

        financialInfo.TotalProjectedSaleAmount=0;


        if(dealContext.Model!=null) {
            financialInfo.BaseModelPrice=dealContext.Model.Price__c;
            financialInfo.TotalProjectedSaleAmount+= financialInfo.BaseModelPrice;
        }

        if(dealContext.Lot!=null) {
            financialInfo.LotPrice=dealContext.Lot.Price__c;
            financialInfo.LotPremium=dealContext.Lot.Premium__c;

            financialInfo.TotalOptionsAmount=dealContext.Lot.Preconfigured_Options_Amount__c;

           
           if(financialInfo.LotPrice!=null){
                financialInfo.TotalProjectedSaleAmount+= financialInfo.LotPrice;
           }

           if(financialInfo.LotPremium!=null){
                financialInfo.TotalProjectedSaleAmount+= financialInfo.LotPremium;
           }

            if(financialInfo.TotalOptionsAmount!=null) {
                financialInfo.TotalProjectedOptionsAmount=financialInfo.TotalOptionsAmount;
                financialInfo.TotalProjectedSaleAmount+=financialInfo.TotalProjectedOptionsAmount;
            }

            if(dealContext.Lot.Base_Model_Price_Override__c!=null)
            {
                financialInfo.TotalProjectedSaleAmount-= financialInfo.BaseModelPrice; 
                financialInfo.BaseModelPrice=dealContext.Lot.Base_Model_Price_Override__c;  
                financialInfo.TotalProjectedSaleAmount+= financialInfo.BaseModelPrice;              
            }
        }


        setOpportunityAmounts(opp, financialInfo);
    }


     public static void setOpportunityAmounts(Opportunity opp, NewstarDealFinancialInfo financialInfo) {
        
        if(financialInfo.BaseModelPrice!=null)
            opp.Base_Model_Price__c=financialInfo.BaseModelPrice;
        
        if(financialInfo.LotPrice!=null)
            opp.Lot_Price__c=financialInfo.LotPrice;

        if(financialInfo.LotPremium!=null)
            opp.Lot_Premium__c=financialInfo.LotPremium;

        if(financialInfo.TotalOptionsAmount!=null)
            opp.Total_Options_Amount__c=financialInfo.TotalOptionsAmount;

        if(financialInfo.TotalDiscountAmount!=null)
            opp.Total_Discount_Amount__c=financialInfo.TotalDiscountAmount;

        if(financialInfo.TotalTaxAmount!=null)
            opp.Total_Tax_Amount__c=financialInfo.TotalTaxAmount;

        if(financialInfo.TotalTaxRebateAmount!=null)
            opp.Total_Tax_Rebate_Amount__c=financialInfo.TotalTaxRebateAmount;      

        if(financialInfo.TotalMortgageIncentive!=null)
            opp.Total_Mortgage_Incentive__c=financialInfo.TotalMortgageIncentive;

        if(financialInfo.TotalMortgageIncentiveIncluded!=null)
            opp.Total_Mortgage_Incentive_Included__c=financialInfo.TotalMortgageIncentiveIncluded;

        if(financialInfo.TotalActualSaleAmount!=null)
            opp.Total_Actual_Sale_Amount__c=financialInfo.TotalActualSaleAmount;

        if(financialInfo.TotalProjectedOptionsAmount!=null)
            opp.Total_Projected_Options_Amount__c=financialInfo.TotalProjectedOptionsAmount;

        if(financialInfo.TotalProjectedDiscountAmount!=null)
            opp.Total_Projected_Discount_Amount__c=financialInfo.TotalProjectedDiscountAmount;

        if(financialInfo.TotalProjectedTaxAmount!=null)
            opp.Total_Projected_Tax_Amount__c=financialInfo.TotalProjectedTaxAmount;

        if(financialInfo.TotalProjectedMortgageIncentive!=null)
            opp.Total_Projected_Mortgage_Incentive__c=financialInfo.TotalProjectedMortgageIncentive;
                         
        if(financialInfo.TotalProjectedMortgageIncentiveIncluded!=null)
            opp.Total_Proj_Mortg_Incent_Incl__c=financialInfo.TotalProjectedMortgageIncentiveIncluded;

        if(financialInfo.TotalProjectedTaxRebateAmount!=null)
            opp.Total_Projected_Tax_Rebate_Amount__c=financialInfo.TotalProjectedTaxRebateAmount;      

        if(financialInfo.TotalProjectedSaleAmount!=null)
            opp.Total_Projected_Sale_Amount__c=financialInfo.TotalProjectedSaleAmount;      

        if(financialInfo.TotalScheduledDeposit!=null)
            opp.Total_Scheduled_Deposit__c=financialInfo.TotalScheduledDeposit;

        if(financialInfo.TotalReceivedDeposit!=null)
            opp.Total_Received_Deposit__c=financialInfo.TotalReceivedDeposit;

        if(financialInfo.TotalDepositDue!=null)
            opp.Total_Deposit_Due__c=financialInfo.TotalDepositDue;
     } 


    public static NewstarDealContext getDealContext(Opportunity opp) {
        return getDealContext(opp, null);
    }


    public static NewstarDealContext getDealContext(Opportunity opp, Map<Id, Account> parentCustomerAccountMap) {
      
        NewstarDealContext dealContext=new NewstarDealContext();

        if(opp.Marketing_Community__c!=null) {
          //dealContext.MarketingCommunity=[SELECT Id, Name, Sales_Process_Type__c FROM Marketing_Community__c WHERE Id=: opp.Marketing_Community__c LIMIT 1];
            dealContext.MarketingCommunity=new CachedCollections().getCachecommunityMapIdsExtended.get(opp.Marketing_Community__c);

        }
      
        if(opp.Subdivision__c!=null){
            dealContext.Subdivision=[SELECT Name FROM Subdivision__c WHERE Id=: opp.Subdivision__c LIMIT 1];
        }
       
        
        if(opp.Lot__c!=null) {
            dealContext.Lot=[SELECT Name, Price__c, Premium__c, Base_Model_Price_Override__c, Preconfigured_Options_Amount__c FROM Lot__c WHERE Id=: opp.Lot__c LIMIT 1];
        } 

        
        if(opp.Model__c!=null) {
            dealContext.Model=[SELECT Name, Price__c FROM Model__c WHERE Id=: opp.Model__c LIMIT 1];
        } 

        if(parentCustomerAccountMap==null) 
        {
            dealContext.CustomerAccount=[SELECT Name FROM Account WHERE Id=: opp.AccountId LIMIT 1];
        }
        else {
            dealContext.CustomerAccount=parentCustomerAccountMap.get(opp.Id);
        }
       

        return dealContext;
    }

}