objects/Lot__c.object
<CustomObject>
    <fields>
        <fullName>Assigned_Model__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Assigned Model</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>The model should belong to the parent subdivision of the lot.</errorMessage>
            <filterItems>
                <field>Model__c.Subdivision__c</field>
                <operation>equals</operation>
                <valueField>$Source.Subdivision__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Model__c</referenceTo>
        <relationshipLabel>Lots</relationshipLabel>
        <relationshipName>Lots</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Newstar_ID__c</fullName>
        <externalId>true</externalId>
        <label>Newstar ID</label>
        <length>32</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Preconfigured_Options_Amount__c</fullName>
        <label>Preconfigured Options Amount</label>
        <precision>11</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Premium__c</fullName>
        <label>Premium</label>
        <precision>11</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Price__c</fullName>
        <label>Price</label>
        <precision>11</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Released_for_Construction__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Released for Construction</description>
        <label>Released for Construction</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Released_for_Sale__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Released for Sale</description>
        <label>Released for Sale</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                </value>
                <value>
                    <fullName>Sold</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Street_Address__c</fullName>
        <label>Street Address</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Subdivision__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Subdivision</label>
        <referenceTo>Subdivision__c</referenceTo>
        <relationshipLabel>Lots</relationshipLabel>
        <relationshipName>Lots</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Total_Price__c</fullName>
        <formula>IF( (TEXT(Type__c) =='Spec' || TEXT(Type__c) =='Model'), Assigned_Model__r.Price__c + Price__c + Premium__c + Preconfigured_Options_Amount__c, NULL)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Total Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Regular</fullName>
                </value>
                <value>
                    <fullName>Spec</fullName>
                </value>
                <value>
                    <fullName>Model</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Lot</label>
    <nameField>
        <label>Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Lots</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Marketing_Community__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Should this Community be included in reports?</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <description>SiteCore/CMS "marketing community"</description>
    <label>Marketing Community</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Marketing Communities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Model__c.object
<CustomObject>
    <fields>
        <fullName>Baths__c</fullName>
        <label>Baths</label>
        <precision>1</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Beds__c</fullName>
        <label>Beds</label>
        <precision>1</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Floors__c</fullName>
        <label>Floors</label>
        <precision>1</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Garages__c</fullName>
        <label>Garages</label>
        <precision>1</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Half_Baths__c</fullName>
        <label>Half Baths</label>
        <precision>1</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Is_Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Is Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Newstar_ID__c</fullName>
        <externalId>true</externalId>
        <label>Newstar ID</label>
        <length>32</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Price__c</fullName>
        <label>Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Sq_Ft__c</fullName>
        <label>Sq. Ft.</label>
        <precision>9</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Subdivision__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Subdivision</label>
        <referenceTo>Subdivision__c</referenceTo>
        <relationshipLabel>Models</relationshipLabel>
        <relationshipName>Models</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Model</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Models</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Lot__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Lot</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>(1 AND 2 AND 3 AND 4) OR 5</booleanFilter>
            <errorMessage>Lot must belong to the selected subdivision, be available (open) and be released for sale.</errorMessage>
            <filterItems>
                <field>Lot__c.Subdivision__c</field>
                <operation>equals</operation>
                <valueField>$Source.Subdivision__c</valueField>
            </filterItems>
            <filterItems>
                <field>Lot__c.Released_for_Sale__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <filterItems>
                <field>Lot__c.Status__c</field>
                <operation>equals</operation>
                <value>Open</value>
            </filterItems>
            <filterItems>
                <field>$Source.StageName</field>
                <operation>equals</operation>
                <value>Prospecting, Engagement, Quote/Selection</value>
            </filterItems>
            <filterItems>
                <field>$Source.StageName</field>
                <operation>equals</operation>
                <value>Contract Ready, Lot Reservation, Pending Offer, Under Contract, Closed Home, Cancelled, Quote Closed</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Lot__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Model__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Model</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Model must belong to the selected subdivision and must be active.</errorMessage>
            <filterItems>
                <field>Model__c.Subdivision__c</field>
                <operation>equals</operation>
                <valueField>$Source.Subdivision__c</valueField>
            </filterItems>
            <filterItems>
                <field>Model__c.Is_Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Model__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Newstar_ID__c</fullName>
        <externalId>true</externalId>
        <label>Newstar ID</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Scenario_Name__c</fullName>
        <label>Scenario Name</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>StageName</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>No Response</fullName>
                </value>
                <value>
                    <fullName>Responded</fullName>
                </value>
                <value>
                    <fullName>Responded Nurture</fullName>
                </value>
                <value>
                    <fullName>Unattended Tour</fullName>
                </value>
                <value>
                    <fullName>Confirmed Appointment</fullName>
                </value>
                <value>
                    <fullName>Missed Appointment</fullName>
                </value>
                <value>
                    <fullName>Site Visited</fullName>
                </value>
                <value>
                    <fullName>Contingent</fullName>
                </value>
                <value>
                    <fullName>Purchased</fullName>
                </value>
                <value>
                    <fullName>Prequalified</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Subdivision__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Project</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Subdivision must belong to the selected sales office and the selected marketing community.</errorMessage>
            <filterItems>
                <field>Subdivision__c.Sales_Office__c</field>
                <operation>equals</operation>
                <valueField>$Source.Sales_Office__c</valueField>
            </filterItems>
            <filterItems>
                <field>Subdivision__c.Marketing_Community__c</field>
                <operation>equals</operation>
                <valueField>$Source.Marketing_Community__c</valueField>
            </filterItems>
            <infoMessage>Select a subdivision</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Subdivision__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Special_Offer__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Banner_Special__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Banner Special</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Expiry_Date__c</fullName>
        <label>Expiry Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Subdivision__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Subdivision</label>
        <referenceTo>Subdivision__c</referenceTo>
        <relationshipLabel>Special Offers</relationshipLabel>
        <relationshipName>Special_Offers</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Special Offer</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Special Offers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Subdivision__c.object
<CustomObject>
    <fields>
        <fullName>Is_Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Is Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Newstar_ID__c</fullName>
        <externalId>true</externalId>
        <label>Newstar ID</label>
        <length>32</length>
        <type>Text</type>
    </fields>
    <description>NEWSTAR Sales Subdivision</description>
    <label>Project</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/NewstarSubdivisionExplorerService.cls
public class NewstarSubdivisionExplorerService {
   
    /*
        Returns a list of lots available in context of the specific opportunity.EventBus

        @param opportunityId ID of the opportunity
    */
    public static NewstarSubdivisionExplorerData getExplorerDataForOpportunity(Id opportunityId) {
        
        Opportunity opp=NewstarContractInformationService.getOpportunity(opportunityId);

        NewstarSubdivisionExplorerData explorerData=new NewstarSubdivisionExplorerData();

        //only return available lots released for sale
        explorerData.lots=[
            SELECT
                Id,
                Name,
                Type__c,
                Street_Address__c,
                Released_for_Sale__c,
                Released_for_Construction__c,
                Assigned_Model__r.Name,
                Total_Price__c,
                Premium__c,
                Price__c,
                Preconfigured_Options_Amount__c
            FROM
                Lot__c
            WHERE 
                Subdivision__c =: opp.Subdivision__c
                AND
                Released_For_Sale__c=true
                AND
                Status__c='Open'
            ORDER BY
                Name ASC
        ];


        //models
        //TODO: exclude inactive models
        explorerData.models=[
            SELECT
                Id,
                Name,
                Price__c,
                Beds__c,
                Baths__c,
                Half_Baths__c,
                Garages__c,
                Floors__c,
                Sq_Ft__c
            FROM
                Model__c
            WHERE 
                Subdivision__c =: opp.Subdivision__c
                AND 
                Model__c.Is_Active__c = true
            ORDER BY 
                Name ASC
        ];

        //special offers that either do NOT an expiry date or have not expired
        Date todayDate=System.Date.today();

        explorerData.specialOffers=[
            SELECT
                Id,
                Name,
                Description__c,
                Expiry_Date__c,
                Active__c,
                Banner_Special__c
            FROM
                Special_Offer__c
            WHERE 
                Subdivision__c =: opp.Subdivision__c
                AND
                Active__c=: true
                AND
                (
                    Expiry_Date__c =: null
                    OR
                    Expiry_Date__c >=: todayDate
                )
            ORDER BY
                Name ASC
        ];


        List<String> stagesToReturnAsAlternates=new List<String>();

        stagesToReturnAsAlternates.add(NewstarSalesPipelineStage.ProspectingStage.Name);
        stagesToReturnAsAlternates.add(NewstarSalesPipelineStage.EngagementStage.Name);
        stagesToReturnAsAlternates.add(NewstarSalesPipelineStage.QuoteSelectionStage.Name);
        stagesToReturnAsAlternates.add(NewstarSalesPipelineStage.ContractReadyStage.Name);
        stagesToReturnAsAlternates.add(NewstarSalesPipelineStage.LotReservationStage.Name);
        stagesToReturnAsAlternates.add(NewstarSalesPipelineStage.PendingOfferStage.Name);

        //alternate opportunities (quotes/scenarios)
        explorerData.alternateOpportunities=[
            SELECT
                Id,
                Name,
                Scenario_Name__c,
                StageName,
                Newstar_ID__c,
                Total_Sale_Amount__c
            FROM
                Opportunity
            WHERE
                AccountId=:opp.AccountId
                AND
                Lot__c=:opp.Lot__c
                AND
                Lot__c!=null
                AND
                Subdivision__c!=null
                AND
                Subdivision__c=:opp.Subdivision__c
               
                AND
                StageName IN : stagesToReturnAsAlternates
            ORDER BY
                Name ASC
        ];

        explorerData.currentOpportunity=NewstarContractInformationService.getOpportunity(opportunityId);

        if(explorerData.currentOpportunity.Marketing_Community__c!=null) {
            explorerData.availableSubdivisions=[
                SELECT
                    Id,
                    Name
                FROM
                    Subdivision__c
                WHERE
                    Is_Active__c =:true
                    AND
                    Marketing_Community__c =: explorerData.currentOpportunity.Marketing_Community__c
                ORDER BY
                    Name
            ];
        }


        return explorerData;

    }


    public static SubdivisionExplorerActionResult setOpportunityLot(Id opportunityId, Id lotId) {

        SubdivisionExplorerActionResult result=new SubdivisionExplorerActionResult();

        Opportunity opp=NewstarContractInformationService.getOpportunity(opportunityId);

        Lot__c lot=getLotDetails(lotId);

        //check if lot type is spec or model
        if(isLotSpecOrModel(lot)) {

            //add a warning if the current model on the opportunity is set is NOT the one associated with the spec lot
            if(opp.Model__c!=null && opp.Model__c!=lot.Assigned_Model__c)
            {
                result.AdditionalWarningMessage='The opportunity model has been set to: ' +lot.Assigned_Model__r.Name+' based on the spec home on the selected lot: '+lot.Name;
            }
           
            //auto-set the opportunity's model to the model pre-assign to the lot
            opp.Model__c=lot.Assigned_Model__c;

        }
        //regular lot with a pre-sited model and the opportunity's model is already set to a different model
        else if(lot.Assigned_Model__c!=null ) {
      
            if(opp.Model__c!=null && opp.Model__c!=lot.Assigned_Model__c){
                result.AdditionalWarningMessage='The opportunity model has been set to: ' +lot.Assigned_Model__r.Name+' based on the pre-sited model on the selected lot: '+lot.Name;
            }
       
            opp.Model__c=lot.Assigned_Model__c;
        }

        opp.Lot__c=lotId;
        opp.IsAutomatedStageUpdate__c=true;

        try {
            update opp;
            result.Message='Lot '+lot.Name+' assigned to opportunity '+opp.Name;
        }
        catch(Exception e) {
            throw new NewstarContractOperationException('Error updating opportunity record: '+ e.getMessage()); 
        }

        return result;
    }



    /*
        Attempts to set the specified model on the specified opportunity.

        @param opportunityId
        @param modelId
    */
    public static SubdivisionExplorerActionResult setOpportunityModel(Id opportunityId, Id modelId) {

        SubdivisionExplorerActionResult result=new SubdivisionExplorerActionResult();

        Opportunity opp=NewstarContractInformationService.getOpportunity(opportunityId);

        Model__c model=getModelDetails(modelId);

        //important: lot may not be assigned yet
        Lot__c lot=getLotDetails(opp.Lot__c);

        //check if the lot is a spec or model and verify that in this case the model being set is the same
        if( lot!=null 
            && isLotSpecOrModel(lot)
            && lot.Assigned_Model__c!=modelId
        )
        {
            opp.Lot__c=null;
            result.AdditionalWarningMessage='The selected model: '+model.Name+' is not compatible with the opportunity\'s assigned spec lot: '+lot.Name+'. The lot has been automatically reset; please select a compatible lot again.'; 
        }
        //check if the lot is regular, but has a pre-sited model
        else if(
            lot!=null 
            && lot.Assigned_Model__c!=null
            && lot.Assigned_Model__c!=modelId
            ){
            opp.Lot__c=null;
            result.AdditionalWarningMessage='The selected model: '+model.Name+' is not compatible with the opportunity\'s assigned regular lot: '+lot.Name+' which specifies a pre-sited model. The lot has been automatically reset; please select a compatible lot again.'; 
        }

        //assign the model
        opp.Model__c=modelId;

        //ensure that the processing pipeline seems this an automated update
        opp.IsAutomatedStageUpdate__c=true;

        try {
            update opp;
            result.Message='Model '+model.Name+' assigned to opportunity '+opp.Name;
        }
        catch(Exception e) {
            throw new NewstarContractOperationException('Error updating opportunity record: '+ e.getMessage()); 
        }

        return result;
    }



    /*
        Attempts to set the specified subdivision on the specified opportunity.

        @param opportunityId
        @param subdivisionId
    */
    public static SubdivisionExplorerActionResult setOpportunitySubdivision(Id opportunityId, Id subdivisionId) {

        SubdivisionExplorerActionResult result=new SubdivisionExplorerActionResult();

        Opportunity opp=NewstarContractInformationService.getOpportunity(opportunityId);

        //assign the subdivision
        opp.Subdivision__c=subdivisionId;

        //ensure that the processing pipeline seems this an automated update
        opp.IsAutomatedStageUpdate__c=true;

        try {
            update opp;
            result.Message='Project updated successfully';
        }
        catch(Exception e) {
            throw new NewstarContractOperationException('Error updating opportunity record: '+ e.getMessage()); 
        }

        return result;
    }



    private static Lot__c getLotDetails(Id lotId) {

        List<Lot__c> lots=[
            SELECT
                Id,
                Name,
                Type__c,
                Assigned_Model__c,
                Assigned_Model__r.Name
            FROM
                Lot__c
            WHERE
                Id =: lotId
            LIMIT 1
        ];

        if(lots.size()==1){
            return lots[0];
        }

        return null;
    }


    private static Model__c getModelDetails(Id modelId) {

        List<Model__c> models=[
            SELECT
                Id,
                Name
            FROM
                Model__c
            WHERE
                Id =: modelId
            LIMIT 1
        ];

        if(models.size()==1){
            return models[0];
        }

        return null;
    }


    private static Boolean isLotSpecOrModel(Lot__c lot) {
        return lot.Type__c=='Spec' || lot.Type__c=='Model';
    }

}